services:
  app:
    build:
      context: ..
    container_name: rag_app
    env_file:
      - ../.env
    volumes:
      - ../:/app
    depends_on:
      pgvector:
        condition: service_healthy
    # Keep the container running and allow interactive shell
    tty: true
    stdin_open: true

  pgvector:
    image: pgvector/pgvector:0.8.1-pg17-trixie
    container_name: rag_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "${PG_PORT:-5433}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata: